---
  #Create a MySQL User and password.  For this it just allows all privs
  - name: Setup MySQL DB
    mysql_db: name=rj state=present
  - name: Setup MySQL User
    mysql_user: name={{ mysqluser }} password={{ mysqlpassword }} priv=*.*:ALL state=present

  #Ignoring Setup of Users and Perms or Symlinks Delete the /var/www/html 
  - name: Remove /var/www/html
    file: path=/var/www state=absent
  

  #Pull Code from Git into /var/www/html
  - name: Pull RJ Code from git
    git: repo=https://github.com/MrMitch17/rjtestcode.git
         dest=/var/www/html
         accept_hostkey=True
  #Reload Apache2
  - name: Reload Apache to serve new code
    service: name=apache2 state=reloaded
  
  #Test for MD5
  - name: Grab Web content to variable
    action: uri url=http://localhost return_content=yes
    register: webpage
  #Skipps if it returns the correct MD5
  - name: Test the MD5
    fail: msg='Did not return the MD5'
    when: "'5eb63bbbe01eeed093cb22bb8f5acdc3' not in webpage.content"
